// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHkSwTd3YIFPoGNmuIXYaEeUwr8bGn9E',
    appId: '1:508918153243:web:4a0d33295dc74b6c1338be',
    messagingSenderId: '508918153243',
    projectId: 'charibazarapp',
    authDomain: 'charibazarapp.firebaseapp.com',
    storageBucket: 'charibazarapp.appspot.com',
    measurementId: 'G-JL83CQHVW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_GnLNs5XSyGOUOz-2iTY17Mh7e7dR9E',
    appId: '1:508918153243:android:baff31b52d2f21501338be',
    messagingSenderId: '508918153243',
    projectId: 'charibazarapp',
    storageBucket: 'charibazarapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCizn-DtnoCIEEDdi2-8BnbxK6FN65PjQ4',
    appId: '1:508918153243:ios:0d87a4a97ec101411338be',
    messagingSenderId: '508918153243',
    projectId: 'charibazarapp',
    storageBucket: 'charibazarapp.appspot.com',
    androidClientId: '508918153243-armbpsatr5pcj9vdmhoqoce8m5rklkud.apps.googleusercontent.com',
    iosClientId: '508918153243-ab9tpsv4m103lfg9pnbce2lje8h7mkgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.charibazarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCizn-DtnoCIEEDdi2-8BnbxK6FN65PjQ4',
    appId: '1:508918153243:ios:0d87a4a97ec101411338be',
    messagingSenderId: '508918153243',
    projectId: 'charibazarapp',
    storageBucket: 'charibazarapp.appspot.com',
    androidClientId: '508918153243-armbpsatr5pcj9vdmhoqoce8m5rklkud.apps.googleusercontent.com',
    iosClientId: '508918153243-ab9tpsv4m103lfg9pnbce2lje8h7mkgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.charibazarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqHkSwTd3YIFPoGNmuIXYaEeUwr8bGn9E',
    appId: '1:508918153243:web:558336ea709fe2531338be',
    messagingSenderId: '508918153243',
    projectId: 'charibazarapp',
    authDomain: 'charibazarapp.firebaseapp.com',
    storageBucket: 'charibazarapp.appspot.com',
    measurementId: 'G-JZKDWR69W2',
  );

}